NAME = libftprintf.a
CC = cc
CFLAGS = -Wall -Werror -Wextra
SRCS = 		ft_printf.c\
		ft_print_char.c\
		print_hex.c\
		print_int.c\
		print_str.c\
		print_maj_hex.c\
		print_min_hex.c\
OBJ = $(SRCS:.c=.o)

all : $(NAME)


